### ISSUE TITLE
Convert client Project to Angular

### ISSUE THREAD

**Issue by stheid** [upb-flunkyteam/flunkysimulator#104]

**Comment by moreApi** [comment]
But the newer one right?

**Comment by stheid** [comment]
the newer one??? Right now i have not started porting, so i will start with the most recent version of curse

**Comment by moreApi** [comment]
I have heard there is a new and an old angular. I'm not sure what the current state of your research is, but do you maybe want to talk to a webdev friend of mine about frameworks?

**Comment by moreApi** [comment]
I think he is currently also using angular one and two, but maybe he can advise us on what framework to use.

**Comment by stheid** [comment]
The "old" angular is 5 years old. it is called angular.js. i am planing to port it tu angular 8 which is the current version

**Comment by stheid** [comment]
I dont think that dis is of any intersting anymore. the OO rework of the client is good in my opinion
