### ISSUE TITLE
Duplicate video window while playing

### ISSUE THREAD

**Issue by moreApi** [upb-flunkyteam/flunkysimulator#109]
Sometimes while a Video is playing another video window appears above it and moves the original video down sometimes even out of the visible frame thereby hiding whether the throw has hit.

![image](https://user-images.githubusercontent.com/10872331/83006467-8cc81600-a012-11ea-9657-bf0295fd10ea.png) (taken with Opera, but other also reported this problem) 

Maybe a quick fix would be to enforce that throwing videos are alwas at the top and if there are any other videos they are below it.

**Comment by moreApi** [comment]
Also pasting pictures in github works really well. Ü

**Comment by ApolloLV** [comment]
I like the idea of reordering for a quick fix.

Another idea is to actually overlay the videos and instead of hiding them to bring the currently playing video to front.

**Comment by stheid** [comment]
perhaps this is related to my sugestion in  #96

**Comment by moreApi** [comment]
seems to be fixed. At least it did not happen to me recently.
