### ISSUE TITLE
Rename SwitchTeam proto

### ISSUE THREAD

**Issue by stheid** [upb-flunkyteam/flunkysimulator#11]
The current behaviour is more a "assign to team"

However resetGame() will overwrite the assigned time, which makes this function quite useless.

Than it might make more sense to call this function "make aktive"

However finally we will need functionallity to assign players to specific teams.

**Comment by stheid** [comment]
@moreApi What are your thoughts on that. is this even up to date?

**Comment by moreApi** [comment]
sry I seem to have overlooked this issue. Should be better now
