### ISSUE TITLE
Play Strafbier Video

### ISSUE THREAD

**Issue by ApolloLV** [upb-flunkyteam/flunkysimulator#111]
We could add another video category of a strafbier which is played when the number of strafbiere of a team is increased

**Comment by stheid** [comment]
But how would you suggest creating such a video without harming beers?

**Comment by ApolloLV** [comment]
I filled a beer bottle with water, don't worry!
I just shot 3 Videos of Strafbier situations today and will be uploading them to the owncloud folder later today.
One of them is the player kicking the beer, the other two is the ball hitting the beer from the opposite side.

**Comment by moreApi** [comment]
Please put the videos in the folder "strafbier"
