### ISSUE TITLE
Display Backend Connection Status and try to reconnect

### ISSUE THREAD

**Issue by ApolloLV** [upb-flunkyteam/flunkysimulator#112]
Currently all information about connection failures to the backend or the video server are only logged to the browser console. We should at least display a popup if the stream registration fails. There is no way to recover in that case and the user should be advised to check the internet connection and reload the page.

**Comment by stheid** [comment]
or call the [tech-support](https://www.youtube.com/watch?v=RQO9K_9w4O0)

**Comment by jharbig** [comment]
For the usability it would be more convenient to only display a symbol for disconnected people and not for connected ones.

**Comment by moreApi** [comment]
I agree. Generally the icon(s) need improvement. But for debug purposes this form was choosen for dev.

**Comment by moreApi** [comment]
Its not perfect but working. We need to observe it a bit to workout the last kinks. Eg. swiss internet fake disconnects
