### ISSUE TITLE
Authentication with common secret via grpc header/metadata

### ISSUE THREAD

**Issue by moreApi** [upb-flunkyteam/flunkysimulator#29]
The player chooses upon logging in his name and a secret/the secret gets autogenerated.
This gets transmitted to the server at registration and saved there. Every (game state changing) request from the client has those two in the request header. The server uses this information then to authenticate the request. On sever side this can easily implement leveraging grpc's interceptor functionality. On client side session cookies can be used to store the name and secret.

Advantage of letting the player choose his secret:
- Can take his session to other devices/browsers

Advantage of autogenrating:
- Players are dumb

Remark:
If the player can choose his secret tell him in very clear words to not use his default pasword. Its not secured and we dont want it.

Links:
https://kuros.in/grpc/2019/01/grpc-interceptors/
https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/header
https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md

**Comment by ApolloLV** [comment]
I am quite unsure how to go about this. If the web client saves this secret as a cookie, it might become very difficult to switch users or have multiple tabs open without messing up this state.
I guess the more fundamental question is: How simple can we make the application while preventing unintended or intended malicious behavior?

**Comment by moreApi** [comment]
We dont need to do the cookie thing. Also then we probaly would need one of those anoying banners. :D

**Comment by moreApi** [comment]
https://github.com/saturnism/grpc-by-example-java/blob/beda853d2a06071bc43f68be69034b9f1c126ee7/metadata-context-example/src/main/java/com/example/grpc/server/JwtServerInterceptor.java#L36 also interesting for server

**Comment by moreApi** [comment]
https://bestofjs.org/projects/grpc-web Ctrl+F "metadata" looks like adding metadata to a call from JS seems to be very easy.
