### ISSUE TITLE
Backend deployment?

### ISSUE THREAD

**Issue by sessfeld** [upb-flunkyteam/flunkysimulator#32]
How ist the backend deployed? Would there be interest in containarizing the application together with the gRPC-Web proxy?

**Comment by ApolloLV** [comment]
Right now it is all set up manually on the server of a friend of @moreApi. Hosting in the cloud would be wellcome change, though.

**Comment by ApolloLV** [comment]
Also, we need to take care of #9, which should also be easier if everything is in a single cloud.
What file hosting options are there at Google? We will be talking about ~200 Videos with 3MB each.

**Comment by sessfeld** [comment]
I don't have a lage amount of free time right now, but I'd recoment [jib](https://github.com/GoogleContainerTools) for the backend.

**Comment by moreApi** [comment]
hosted @stheid with docker
