### ISSUE TITLE
[Protocol] Introducting gamestate enum

### ISSUE THREAD

**Issue by moreApi** [upb-flunkyteam/flunkysimulator#86]
rel #42 for the output

chat excerpt:
>Was haltet ihr von einem generellen State enum? Was dann folgende Werte haben könnte: >NoActiveGame, TeamAThrowing, TeamBThrowing, Resting, TeamAWon, TeamBWon. Später könnte >man dort noch einen Zustand "Abgabe" für #41 hinzufügen"
>und dann fliegt das "isResting" bool natürlich raus

**Comment by stheid** [comment]
that sound extremely good. This is very much in alignment with the rules where we split a turn into 4 phases.
