### ISSUE TITLE
Hiding of the "take over strafbier"-button

### ISSUE THREAD

**Issue by stheid** [upb-flunkyteam/flunkysimulator#89]

**Comment by stheid** [comment]
related to #90

 - players can only rejoin if abgegeben if there are strafbiere in the team
 - players can only rejoin THEMSELFS
 - rejoining automatically reduces strafbiercount

**Comment by stheid** [comment]
> Do we also want to enforce those restrictions in the server?

i would like that

**Comment by moreApi** [comment]
As far as I know our Plan kinda was:
- Version 1: anything to play (Done by Jan)
- Version 2: Distributed Client-Server Game with solid technical base and very loose Rule enforcement to allow easy recovering from faulty game states.
- Version 3: Enforcing Rules and extra features.

We never wrote that down and maybe it was never this clear. Maybe we should put that on the main readme or discuss again. 
This looks to me like Version 3 feature. My suggestion would be to leave it in the JS Client as it is. It is a nice feature to have. And create an issue to implement the restrictions on the backend later once we are satisfied with the technical base. 

To be satisfied with the technical base I would like to have some sort of registering
 eg. connect player names to streams with a shared secret. So people cannot do bad stuff with a spoofed Name.

**Comment by stheid** [comment]
ok, but what is your opinion about disabling the buttons in the client

**Comment by moreApi** [comment]
sounds good
