### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by stheid** [upb-flunkyteam/flunkysimulator#94]
Maybe a more elegant solution to #91 is to really create a login page that the user must pass before he gets onto the game page. this would make the login also much more obvious than it is right now.

clicking on the "switch player" button could clear the current username and relocate user to the login page

**Comment by stheid** [comment]
sugestion was to rather use a modal: https://getbootstrap.com/docs/4.0/components/modal/

**Comment by ApolloLV** [comment]
Quick note: We are using Bootstrap 3, just so you don't get confused when the 4.0 docs don't work.

**Comment by stheid** [comment]
oh, thats an important note. Thanks pointing out

**Comment by moreApi** [comment]
https://www.w3schools.com/howto/howto_css_modals.asp plain js ftw
